name: WEB-EMSCRIPTEN

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  BUILD_TYPE: MinSizeRel

jobs:
  linux-emscripten:
    runs-on: ubuntu-latest
    container:
      image: stateoftheartio/qt6:6.4-wasm-aqt
      options: --user root
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Emscripten version set
        run: emsdk install 3.1.14 ; emsdk activate 3.1.14

      - name: Emscripten Build
        run: qt-cmake ./ -G Ninja -B ./build; cmake --build ./build; cp ./build/morphing.html ./build/index.html

      - name: Rsync
        run: apt update; apt install -y rsync

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/ # The folder the action should deploy.
          single-commit: true
